### PR TITLE
create a readme file in Markdown format

### PR DESCRIPTION
**Pull request by galylee**
create a readme file in Markdown format which is good for adding readme contents. I will enrich the information later.

### CODE REVIEW

**Comment by koichi-szk** [comment]
Nice work.   I found we should add many items.   Installation/Configuration and Run will need a link to pgxc_ctl primer.   Architecture will need a link to XC architecture document, as well as its internals.

Let me upload these documents available now.

Because of the restriction of applaudable files in GitHub, I may upload them to the sourceforge.

Regards;

**Comment by koichi-szk** [comment]
To start with, it looks nice to combine all the initial commits into a single file and commit it as initial file.

How does it sound?

**Comment by galylee** [comment]
sure, it will be good to commit it when it is ready, I will work more on this.

**Comment by koichi-szk** [comment]
Committed.

**Pull request closed without merging**
