### PR TITLE
Issue 143

### PR DESCRIPTION
**Pull request by xuegang**
This fix also fix issue #118. Please review the code, If any problem. Please let me know.

### CODE REVIEW

**Comment by koichi-szk** [comment]
Thanks.   #118 fix has been committed.   #143 fix is a bit log so please let me take some more closer look, maybe tomorrow morning.

Thanks.

**Comment by koichi-szk** [comment]
I review the request and generally, the code is okay.

Please make formatting improvement for example:
1. give space at the both end of operators, 
2. Opening parentheses after if keyword should be put at the next line.
3. In editing code indentation, please be careful that tab stop is supposed to be 4, as in vanilla postgres.

I'd like to receive revised one and fix it locally from JPN.

Sorry for bothering.  Thank you ;
Koichi Suzuki

**Comment by koichi-szk** [comment]
#135 fix is okay.   It has been committed.   Please consider #143 fix reformatting.   Please consider to use tab width as 4, not 8.   This is PG's standard.   Also, please consider to replace leading spaces of each line with tabs.

Regards;

**Comment by xuegang** [comment]
OK, Based on your suggestion. I will do it again

**Comment by koichi-szk** [comment]
Thanks.   I hope it's a piece of cake.   Please maintain basic code.   Just take care of the format.

**Comment by koichi-szk** [comment]
Okay, it has been committed.   Close.

**Pull request closed without merging**
