### PR TITLE
Fix 2fd492d575207243098346dd846ba9b21908bccd  issue according to koichi's  comment

### PR DESCRIPTION
**Pull request by Jasonysli**

### CODE REVIEW

**Comment by koichi-szk** [comment]
I've already committed you previous pull request with additional comments.    To reduce inconsistency, could you make pull request based on the current master, or send me all the affected files?

**Comment by koichi-szk** [comment]
Okay, I will try to merge you one.   It will be easier to merge in the master, then cherry-pick to others.

I hope you don't have to do extra work on it.    I will let you know when your help is needed.

Thanks.

**Comment by koichi-szk** [comment]
Sorry, I found the conflict can be a bit dangerous to merge manually.

Could you provide a patch or pull request based on the current master, or send me varsup.c in e-mail?

This time, I'll wait for your response to avoid inconsistencies.

Thank you and sorry for the inconvenience.

**Comment by koichi-szk** [comment]
I found the whole varsup.c file from your repo.   So maybe I don't need your help.   Sorry for the confusion.

Please understand that the first two pull request, 39590e6 and 8d30c33 have already been merged.   The last one is remaining.

Again, please let me do to include current pull request.

**Comment by koichi-szk** [comment]
Okay,  I was successful to commit this to master, REL1_2_STABLE and REL1_1_STABLE, but not yet to REL1_0_STABLE.

In the case of REL1_0_STABLE, I was successful to commit your previous pull request so I think 1.0.x has the same improvement.

**Comment by Jasonysli** [comment]
Sorry for the inconvenience, my first time use git hub pull request. I will try to merge code base on the latest code.

**Pull request closed without merging**
